### PR TITLE
Changes service to wait the end of system suspend

### PR DESCRIPTION
**Pull request by lpwisniewski**
The service now waits the end of system suspend before launching again. Did not works before this modification for me.

### CODE REVIEW

**Comment by Antoine-Auffret** [comment]
+1 thanks for the tip

**Comment by tiziw** [comment]
[Here's](https://bpaste.net/show/b22b6638ef8a) my systemctl status for systemd-iuvolt.service, suspend.target and sleep.target. To me it looks like the script does get executed after sleep. It doesn't actually start after sleep, it starts before, but when it stops after sleep, ExecStop executes the undervolt command. From what I read at [systemd.special](https://www.freedesktop.org/software/systemd/man/systemd.special.html), sleep.target is pulled by suspend.target and hibernate.target so I think it would add some form of redundancy if we add both sleep.target and suspend.target.

If you could make sure through the use of systemctl status whether the undervolt command is executed or not and/or paste your ouput that could help clear up the situation.

**Comment by Antoine-Auffret** [comment]
It seems for me that the script does get well executed (the values ​​have been changed) only if suspend.target is filled in systemd-iuvolt.service. If sleep.target is filled in, all the values are reset to 0 on sleep or suspend. However, the script seems to be executed anyway with sleep.target but without changing any values :
$ sudo wrmsr 0x150 0x8000001000000000
$ sudo rdmsr 0x150
f0a00000
$ systemctl suspend
$ sudo rdmsr 0x150
0
$ systemctl status systemd-iuvolt.service
● systemd-iuvolt.service - Undervolt cpu                                                                            
   Loaded: loaded (/etc/systemd/system/systemd-iuvolt.service; enabled; vendor preset: enabled)                     
   Active: inactive (dead) since dim. 2018-02-04 00:31:40 CET; 56s ago                                              
  Process: 23090 ExecStop=/usr/bin/iuvolt (code=exited, status=0/SUCCESS)                                           
  Process: 23037 ExecStart=/usr/bin/iuvolt (code=exited, status=0/SUCCESS)                                          
 Main PID: 23037 (code=exited, status=0/SUCCESS)

févr. 04 00:31:40 XPS-13-9360 systemd[1]: Started Undervolt cpu.
févr. 04 00:31:40 XPS-13-9360 iuvolt[23037]: Loaded config! CPU Core : -120mV, GPU : -90mV, Cache : -120mV,
févr. 04 00:31:40 XPS-13-9360 iuvolt[23037]: wrote 0x80000011F0A00000 successful to plane index 0
févr. 04 00:31:40 XPS-13-9360 iuvolt[23037]: wrote 0x80000111F4800000 successful to plane index 1
févr. 04 00:31:40 XPS-13-9360 iuvolt[23037]: wrote 0x80000211F0A00000 successful to plane index 2
févr. 04 00:31:40 XPS-13-9360 iuvolt[23090]: Loaded config! CPU Core : -120mV, GPU : -90mV, Cache : -120mV,
févr. 04 00:31:40 XPS-13-9360 iuvolt[23090]: wrote 0x80000011F0A00000 successful to plane index 0
févr. 04 00:31:40 XPS-13-9360 iuvolt[23090]: wrote 0x80000111F4800000 successful to plane index 1
févr. 04 00:31:40 XPS-13-9360 iuvolt[23090]: wrote 0x80000211F0A00000 successful to plane index 2

**Comment by tiziw** [comment]
That is very strange. I've tested the same commands as you, but for me the systemd service does work as expected. I've tested the systemd script with suspend.target and hibernate.target and it still works. 

I'll add suspend.target and hibernate.target to the service.

**Pull request merged**
